#!/usr/bin/env python3
from pathlib import Path
import json

ROOT = Path.cwd()

def read(rel): return (ROOT / rel).read_text(encoding='utf-8')
def write(rel, text):
    p = ROOT / rel
    p.parent.mkdir(parents=True, exist_ok=True)
    p.write_text(text, encoding='utf-8')
def rep(text, old, new, label):
    if old not in text:
        raise RuntimeError(f'Patch marker not found: {label}')
    return text.replace(old, new, 1)

# VideoSettings.h
p='src/Settings/VideoSettings.h'; s=read(p)
s=rep(s,'    DEFINE_SETTINGFACT(rtspUrl)\n    DEFINE_SETTINGFACT(aspectRatio)\n','''    DEFINE_SETTINGFACT(rtspUrl)\n    DEFINE_SETTINGFACT(hikvisionDualEnabled)\n    DEFINE_SETTINGFACT(hikvisionVehicleModel)\n    DEFINE_SETTINGFACT(hikvisionCam1MainUrl)\n    DEFINE_SETTINGFACT(hikvisionCam1SubUrl)\n    DEFINE_SETTINGFACT(hikvisionCam2MainUrl)\n    DEFINE_SETTINGFACT(hikvisionCam2SubUrl)\n    DEFINE_SETTINGFACT(hikvisionMainStream)\n    DEFINE_SETTINGFACT(aspectRatio)\n''','VideoSettings facts'); write(p,s)

# VideoSettings.cc
p='src/Settings/VideoSettings.cc'; s=read(p)
s=rep(s,'DECLARE_SETTINGSFACT(VideoSettings, disableWhenDisarmed)\n\nDECLARE_SETTINGSFACT_NO_FUNC(VideoSettings, videoSource)\n','''DECLARE_SETTINGSFACT(VideoSettings, disableWhenDisarmed)\nDECLARE_SETTINGSFACT(VideoSettings, hikvisionDualEnabled)\nDECLARE_SETTINGSFACT(VideoSettings, hikvisionVehicleModel)\nDECLARE_SETTINGSFACT(VideoSettings, hikvisionCam1MainUrl)\nDECLARE_SETTINGSFACT(VideoSettings, hikvisionCam1SubUrl)\nDECLARE_SETTINGSFACT(VideoSettings, hikvisionCam2MainUrl)\nDECLARE_SETTINGSFACT(VideoSettings, hikvisionCam2SubUrl)\nDECLARE_SETTINGSFACT(VideoSettings, hikvisionMainStream)\n\nDECLARE_SETTINGSFACT_NO_FUNC(VideoSettings, videoSource)\n''','VideoSettings declarations')
s=rep(s,'''bool VideoSettings::streamConfigured(void)\n{\n    //-- First, check if it's autoconfigured\n''','''bool VideoSettings::streamConfigured(void)\n{\n    if (hikvisionDualEnabled()->rawValue().toBool()) {\n        const bool useMain = hikvisionMainStream()->rawValue().toBool();\n        const QString cam1 = useMain ? hikvisionCam1MainUrl()->rawValue().toString() : hikvisionCam1SubUrl()->rawValue().toString();\n        const QString cam2 = useMain ? hikvisionCam2MainUrl()->rawValue().toString() : hikvisionCam2SubUrl()->rawValue().toString();\n        return !cam1.isEmpty() || !cam2.isEmpty();\n    }\n    //-- First, check if it's autoconfigured\n''','streamConfigured'); write(p,s)

# metadata
p='src/Settings/Video.SettingsGroup.json'; d=json.loads(read(p)); facts=d['QGC.MetaData.Facts']
new=[
 {'name':'hikvisionDualEnabled','shortDesc':'Enable the custom two-camera Hikvision vehicle profile.','longDesc':'Uses two independent RTSP receivers. Both cameras switch together between SUB and MAIN streams.','type':'bool','default':False,'label':'Enable Dual Hikvision','keywords':'hikvision,dual camera,vehicle model'},
 {'name':'hikvisionVehicleModel','shortDesc':'Name of this vehicle/camera profile.','longDesc':'Friendly name used for the dual Hikvision vehicle profile.','type':'string','default':'Змій','label':'Vehicle Model','keywords':'vehicle model,profile,hikvision'},
 {'name':'hikvisionCam1MainUrl','shortDesc':'Camera 1 MAIN RTSP URL.','longDesc':'Hikvision camera 1 main stream, typically /Streaming/Channels/101.','type':'string','default':'','label':'Camera 1 MAIN URL','keywords':'hikvision,camera 1,main,rtsp'},
 {'name':'hikvisionCam1SubUrl','shortDesc':'Camera 1 SUB RTSP URL.','longDesc':'Hikvision camera 1 sub stream, typically /Streaming/Channels/102.','type':'string','default':'','label':'Camera 1 SUB URL','keywords':'hikvision,camera 1,sub,rtsp'},
 {'name':'hikvisionCam2MainUrl','shortDesc':'Camera 2 MAIN RTSP URL.','longDesc':'Hikvision camera 2 main stream, typically /Streaming/Channels/101.','type':'string','default':'','label':'Camera 2 MAIN URL','keywords':'hikvision,camera 2,main,rtsp'},
 {'name':'hikvisionCam2SubUrl','shortDesc':'Camera 2 SUB RTSP URL.','longDesc':'Hikvision camera 2 sub stream, typically /Streaming/Channels/102.','type':'string','default':'','label':'Camera 2 SUB URL','keywords':'hikvision,camera 2,sub,rtsp'},
 {'name':'hikvisionMainStream','shortDesc':'Start the dual Hikvision profile in MAIN instead of SUB.','longDesc':'This state is also changed by the MAIN/SUB button on the Fly view.','type':'bool','default':False,'label':'Use MAIN Stream','keywords':'hikvision,main,sub,stream'}]
existing={f['name'] for f in facts}; pos=next((i+1 for i,f in enumerate(facts) if f.get('name')=='rtspUrl'),len(facts))
for item in reversed(new):
    if item['name'] not in existing: facts.insert(pos,item)
write(p,json.dumps(d,ensure_ascii=False,indent=4)+'\n')

# Settings UI
p='src/AppSettings/pages/Video.SettingsUI.json'; d=json.loads(read(p)); d['bindings']['dualHikvisionEnabled']='QGroundControl.settingsManager.videoSettings.hikvisionDualEnabled.rawValue'
for g in d['groups']:
    if g.get('heading')=='Video Source': g['showWhen']='!dualHikvisionEnabled'
    if g.get('heading')=='Connection': g['showWhen']='!sourceDisabled && !autoStreamConfig && !dualHikvisionEnabled'
g={'heading':'Vehicle Model / Dual Hikvision','keywords':['vehicle model','hikvision','dual camera','main','sub'],'controls':[
 {'setting':'videoSettings.hikvisionDualEnabled'},
 {'setting':'videoSettings.hikvisionVehicleModel','showWhen':'dualHikvisionEnabled'},
 {'setting':'videoSettings.hikvisionCam1MainUrl','showWhen':'dualHikvisionEnabled'},
 {'setting':'videoSettings.hikvisionCam1SubUrl','showWhen':'dualHikvisionEnabled'},
 {'setting':'videoSettings.hikvisionCam2MainUrl','showWhen':'dualHikvisionEnabled'},
 {'setting':'videoSettings.hikvisionCam2SubUrl','showWhen':'dualHikvisionEnabled'},
 {'setting':'videoSettings.hikvisionMainStream','showWhen':'dualHikvisionEnabled'}]}
if not any(x.get('heading')==g['heading'] for x in d['groups']): d['groups'].insert(1,g)
write(p,json.dumps(d,ensure_ascii=False,indent=4)+'\n')

# VideoManager.h
p='src/VideoManager/VideoManager.h'; s=read(p)
s=rep(s,'    Q_PROPERTY(QString  uvcVideoSourceID        READ uvcVideoSourceID                           NOTIFY uvcVideoSourceIDChanged)\n','''    Q_PROPERTY(QString  uvcVideoSourceID        READ uvcVideoSourceID                           NOTIFY uvcVideoSourceIDChanged)\n    Q_PROPERTY(bool     dualHikvisionEnabled     READ dualHikvisionEnabled                        NOTIFY dualHikvisionChanged)\n    Q_PROPERTY(bool     hikvisionMainStream      READ hikvisionMainStream                         NOTIFY hikvisionStreamModeChanged)\n    Q_PROPERTY(bool     secondaryDecoding        READ secondaryDecoding                           NOTIFY secondaryDecodingChanged)\n    Q_PROPERTY(int      primaryHikvisionCamera   READ primaryHikvisionCamera                      NOTIFY hikvisionCameraOrderChanged)\n    Q_PROPERTY(int      secondaryHikvisionCamera READ secondaryHikvisionCamera                    NOTIFY hikvisionCameraOrderChanged)\n''','manager properties')
s=rep(s,'    Q_INVOKABLE void stopRecording();\n    Q_INVOKABLE void stopVideo();\n','''    Q_INVOKABLE void stopRecording();\n    Q_INVOKABLE void stopVideo();\n    Q_INVOKABLE void toggleHikvisionStream();\n    Q_INVOKABLE void swapHikvisionCameras();\n''','manager invokables')
s=rep(s,'    QString uvcVideoSourceID() const { return _uvcVideoSourceID; }\n    void setfullScreen(bool on);\n','''    QString uvcVideoSourceID() const { return _uvcVideoSourceID; }\n    bool dualHikvisionEnabled() const;\n    bool hikvisionMainStream() const;\n    bool secondaryDecoding() const { return _secondaryDecoding; }\n    int primaryHikvisionCamera() const { return _cameraOrderSwapped ? 2 : 1; }\n    int secondaryHikvisionCamera() const { return _cameraOrderSwapped ? 1 : 2; }\n    void setfullScreen(bool on);\n''','manager getters')
s=rep(s,'    void uvcVideoSourceIDChanged();\n    void videoSizeChanged();\n','''    void uvcVideoSourceIDChanged();\n    void videoSizeChanged();\n    void dualHikvisionChanged();\n    void hikvisionStreamModeChanged();\n    void secondaryDecodingChanged();\n    void hikvisionCameraOrderChanged();\n''','manager signals')
s=rep(s,'    bool _updateVideoUri(VideoReceiver *receiver, const QString &uri);\n','''    bool _updateVideoUri(VideoReceiver *receiver, const QString &uri);\n    QString _hikvisionUriForReceiver(const VideoReceiver *receiver) const;\n''','manager uri helper')
s=rep(s,'    QAtomicInteger<bool> _decoding = false;\n','''    QAtomicInteger<bool> _decoding = false;\n    QAtomicInteger<bool> _secondaryDecoding = false;\n''','secondary decoding')
s=rep(s,'    QString _uvcVideoSourceID;\n','''    QString _uvcVideoSourceID;\n    bool _cameraOrderSwapped = false;\n''','camera swap state'); write(p,s)

# VideoManager.cc
p='src/VideoManager/VideoManager.cc'; s=read(p)
s=rep(s,'VideoManager *VideoManager::instance()\n{\n    return _videoManagerInstance();\n}\n\nvoid VideoManager::startVideoBackendInit()\n','''VideoManager *VideoManager::instance()\n{\n    return _videoManagerInstance();\n}\n\nbool VideoManager::dualHikvisionEnabled() const\n{\n    return _videoSettings && _videoSettings->hikvisionDualEnabled()->rawValue().toBool();\n}\n\nbool VideoManager::hikvisionMainStream() const\n{\n    return _videoSettings && _videoSettings->hikvisionMainStream()->rawValue().toBool();\n}\n\nvoid VideoManager::toggleHikvisionStream()\n{\n    if (_videoSettings && dualHikvisionEnabled()) {\n        _videoSettings->hikvisionMainStream()->setRawValue(!hikvisionMainStream());\n    }\n}\n\nvoid VideoManager::swapHikvisionCameras()\n{\n    if (!dualHikvisionEnabled()) return;\n    _cameraOrderSwapped = !_cameraOrderSwapped;\n    emit hikvisionCameraOrderChanged();\n    _videoSourceChanged();\n}\n\nQString VideoManager::_hikvisionUriForReceiver(const VideoReceiver *receiver) const\n{\n    if (!receiver || !_videoSettings || !dualHikvisionEnabled()) return QString();\n    int camera = 0;\n    if (receiver->name() == QStringLiteral("videoContent")) camera = primaryHikvisionCamera();\n    else if (receiver->name() == QStringLiteral("camera2Video")) camera = secondaryHikvisionCamera();\n    else return QString();\n    const bool main = hikvisionMainStream();\n    if (camera == 1) return main ? _videoSettings->hikvisionCam1MainUrl()->rawValue().toString() : _videoSettings->hikvisionCam1SubUrl()->rawValue().toString();\n    return main ? _videoSettings->hikvisionCam2MainUrl()->rawValue().toString() : _videoSettings->hikvisionCam2SubUrl()->rawValue().toString();\n}\n\nvoid VideoManager::startVideoBackendInit()\n''','manager helper implementations')
s=rep(s,'    (void) connect(_videoSettings->rtspUrl(), &Fact::rawValueChanged, this, &VideoManager::_videoSourceChanged);\n    (void) connect(_videoSettings->tcpUrl(), &Fact::rawValueChanged, this, &VideoManager::_videoSourceChanged);\n','''    (void) connect(_videoSettings->rtspUrl(), &Fact::rawValueChanged, this, &VideoManager::_videoSourceChanged);\n    (void) connect(_videoSettings->tcpUrl(), &Fact::rawValueChanged, this, &VideoManager::_videoSourceChanged);\n    const auto hikvisionConfigChanged = [this](const QVariant &) { emit hasVideoChanged(); emit isStreamSourceChanged(); _videoSourceChanged(); };\n    (void) connect(_videoSettings->hikvisionCam1MainUrl(), &Fact::rawValueChanged, this, hikvisionConfigChanged);\n    (void) connect(_videoSettings->hikvisionCam1SubUrl(), &Fact::rawValueChanged, this, hikvisionConfigChanged);\n    (void) connect(_videoSettings->hikvisionCam2MainUrl(), &Fact::rawValueChanged, this, hikvisionConfigChanged);\n    (void) connect(_videoSettings->hikvisionCam2SubUrl(), &Fact::rawValueChanged, this, hikvisionConfigChanged);\n    (void) connect(_videoSettings->hikvisionMainStream(), &Fact::rawValueChanged, this, [this](const QVariant &) { emit hikvisionStreamModeChanged(); _videoSourceChanged(); });\n    (void) connect(_videoSettings->hikvisionDualEnabled(), &Fact::rawValueChanged, this, [this](const QVariant &) { _cameraOrderSwapped = false; emit dualHikvisionChanged(); emit hikvisionCameraOrderChanged(); emit hasVideoChanged(); emit isStreamSourceChanged(); _videoSourceChanged(); });\n''','settings connections')
s=rep(s,'    static const QStringList videoStreamList = {\n        "videoContent",\n        "thermalVideo"\n    };\n','''    static const QStringList videoStreamList = {\n        "videoContent",\n        "thermalVideo",\n        "camera2Video"\n    };\n''','receiver list')
s=rep(s,'bool VideoManager::hasVideo() const\n{\n    return (_videoSettings->streamEnabled()->rawValue().toBool() && _videoSettings->streamConfigured());\n}\n','''bool VideoManager::hasVideo() const\n{\n    if (!_videoSettings->streamEnabled()->rawValue().toBool()) return false;\n    if (dualHikvisionEnabled()) {\n        const bool main = hikvisionMainStream();\n        const QString cam1 = main ? _videoSettings->hikvisionCam1MainUrl()->rawValue().toString() : _videoSettings->hikvisionCam1SubUrl()->rawValue().toString();\n        const QString cam2 = main ? _videoSettings->hikvisionCam2MainUrl()->rawValue().toString() : _videoSettings->hikvisionCam2SubUrl()->rawValue().toString();\n        return !cam1.isEmpty() || !cam2.isEmpty();\n    }\n    return _videoSettings->streamConfigured();\n}\n''','hasVideo')
s=rep(s,'bool VideoManager::isStreamSource() const\n{\n    static const QStringList videoSourceList = {\n','''bool VideoManager::isStreamSource() const\n{\n    if (dualHikvisionEnabled()) return true;\n    static const QStringList videoSourceList = {\n''','isStreamSource')
s=rep(s,'bool VideoManager::autoStreamConfigured() const\n{\n    for (VideoReceiver *receiver : _videoReceivers) {\n','''bool VideoManager::autoStreamConfigured() const\n{\n    if (dualHikvisionEnabled()) return false;\n    for (VideoReceiver *receiver : _videoReceivers) {\n''','autoStreamConfigured')
s=rep(s,'bool VideoManager::_updateAutoStream(VideoReceiver *receiver)\n{\n    const QGCVideoStreamInfo *pInfo = receiver->videoStreamInfo();\n','''bool VideoManager::_updateAutoStream(VideoReceiver *receiver)\n{\n    if (dualHikvisionEnabled()) return false;\n    const QGCVideoStreamInfo *pInfo = receiver->videoStreamInfo();\n''','updateAutoStream')
s=rep(s,'    if (receiver->isThermal()) {\n        return settingsChanged;\n    }\n\n    settingsChanged |= _updateUVC(receiver);\n','''    if (receiver->isThermal()) {\n        return settingsChanged;\n    }\n    if (dualHikvisionEnabled()) {\n        if (receiver->name() == QStringLiteral("videoContent") || receiver->name() == QStringLiteral("camera2Video"))\n            settingsChanged |= _updateVideoUri(receiver, _hikvisionUriForReceiver(receiver));\n        return settingsChanged;\n    }\n    if (receiver->name() == QStringLiteral("camera2Video")) {\n        settingsChanged |= _updateVideoUri(receiver, QString());\n        return settingsChanged;\n    }\n\n    settingsChanged |= _updateUVC(receiver);\n''','updateSettings dual branch')
s=rep(s,'    const QString source = _videoSettings->videoSource()->rawValue().toString();\n    const uint32_t timeout = ((source == VideoSettings::videoSourceRTSP) ? _videoSettings->rtspTimeout()->rawValue().toUInt() : 3);\n\n    receiver->start(timeout);\n','''    const QString source = _videoSettings->videoSource()->rawValue().toString();\n    const bool customRtsp = dualHikvisionEnabled() && (receiver->name() == QStringLiteral("videoContent") || receiver->name() == QStringLiteral("camera2Video"));\n    const uint32_t timeout = ((customRtsp || source == VideoSettings::videoSourceRTSP) ? _videoSettings->rtspTimeout()->rawValue().toUInt() : 3);\n\n    receiver->start(timeout);\n''','startReceiver timeout')
s=rep(s,'        if (!receiver->isThermal()) {\n            _streaming = active;\n            emit streamingChanged();\n        }\n','''        if (receiver->name() == QStringLiteral("videoContent")) {\n            _streaming = active;\n            emit streamingChanged();\n        }\n''','streaming callback')
s=rep(s,'        if (!receiver->isThermal()) {\n            _decoding = active;\n            emit decodingChanged();\n        }\n','''        if (receiver->name() == QStringLiteral("videoContent")) {\n            _decoding = active;\n            emit decodingChanged();\n        } else if (receiver->name() == QStringLiteral("camera2Video")) {\n            _secondaryDecoding = active;\n            emit secondaryDecodingChanged();\n        }\n''','decoding callback')
s=rep(s,'        if (!receiver->isThermal()) {\n            _recording = active;\n            if (!active) {\n                _subtitleWriter->stopCapturingTelemetry();\n            }\n            emit recordingChanged(_recording);\n        }\n','''        if (receiver->name() == QStringLiteral("videoContent")) {\n            _recording = active;\n            if (!active) _subtitleWriter->stopCapturingTelemetry();\n            emit recordingChanged(_recording);\n        }\n''','recording callback')
s=rep(s,'        if (!receiver->isThermal()) {\n            _subtitleWriter->startCapturingTelemetry(filename, videoSize());\n        }\n','''        if (receiver->name() == QStringLiteral("videoContent")) {\n            _subtitleWriter->startCapturingTelemetry(filename, videoSize());\n        }\n''','recordingStarted callback')
s=rep(s,'        if (!receiver->isThermal()) {\n            _videoSize = size;\n            emit videoSizeChanged();\n            emit aspectRatioChanged();\n        }\n','''        if (receiver->name() == QStringLiteral("videoContent")) {\n            _videoSize = size;\n            emit videoSizeChanged();\n            emit aspectRatioChanged();\n        }\n''','videoSize callback'); write(p,s)

# FlyView: second camera above PiP
p='src/FlyView/FlyView.qml'; s=read(p)
s=rep(s,'        FlyViewWidgetLayer {\n            id:                     widgetLayer\n','''        HikvisionSecondVideo {\n            id:                     hikvisionSecondVideo\n            width:                  _pipView.width\n            height:                 _pipView.height\n            anchors.left:           _pipView.left\n            anchors.bottom:         _pipView.top\n            anchors.bottomMargin:   _toolsMargin\n            visible:                QGroundControl.videoManager.dualHikvisionEnabled && QGroundControl.videoManager.hasVideo && _pipView.visible\n            z:                      QGroundControl.zOrderWidgets + 1\n        }\n\n        FlyViewWidgetLayer {\n            id:                     widgetLayer\n''','secondary camera view'); write(p,s)

# FlyViewVideo: SUB/MAIN button
p='src/FlyView/FlyViewVideo.qml'; s=read(p)
s=rep(s,'    QGCLabel {\n        text: qsTr("Double-click to exit full screen")\n','''    Column {\n        anchors.top: parent.top\n        anchors.right: parent.right\n        anchors.margins: ScreenTools.defaultFontPixelHeight * 0.6\n        spacing: ScreenTools.defaultFontPixelHeight * 0.35\n        visible: QGroundControl.videoManager.dualHikvisionEnabled\n        z: 100\n        QGCButton {\n            text: QGroundControl.videoManager.hikvisionMainStream ? qsTr("MAIN") : qsTr("SUB")\n            onClicked: QGroundControl.videoManager.toggleHikvisionStream()\n        }\n        Rectangle {\n            width: cameraLabel.implicitWidth + ScreenTools.defaultFontPixelWidth * 2\n            height: cameraLabel.implicitHeight + ScreenTools.defaultFontPixelHeight * 0.5\n            radius: ScreenTools.defaultFontPixelWidth * 0.5\n            color: Qt.rgba(0,0,0,0.65)\n            QGCLabel { id: cameraLabel; anchors.centerIn: parent; color: "white"; font.bold: true; text: qsTr("CAM %1").arg(QGroundControl.videoManager.primaryHikvisionCamera) }\n        }\n    }\n\n    QGCLabel {\n        text: qsTr("Double-click to exit full screen")\n''','main stream controls'); write(p,s)

# New second camera QML
write('src/FlyView/HikvisionSecondVideo.qml', '''import QtQuick\nimport QtMultimedia\n\nimport QGroundControl\nimport QGroundControl.Controls\n\nItem {\n    id: root\n    clip: true\n    Rectangle { anchors.fill: parent; color: "black" }\n    Image { anchors.fill: parent; source: "/res/NoVideoBackground.jpg"; fillMode: Image.PreserveAspectCrop; visible: !QGroundControl.videoManager.secondaryDecoding }\n    VideoOutput {\n        objectName: "camera2Video"\n        anchors.fill: parent\n        visible: QGroundControl.videoManager.secondaryDecoding\n        fillMode: QGroundControl.settingsManager.videoSettings.videoFit.rawValue === 2 ? VideoOutput.PreserveAspectCrop : VideoOutput.PreserveAspectFit\n    }\n    Rectangle {\n        anchors.left: parent.left; anchors.top: parent.top; anchors.margins: ScreenTools.defaultFontPixelHeight * 0.35\n        width: cameraLabel.implicitWidth + ScreenTools.defaultFontPixelWidth * 2; height: cameraLabel.implicitHeight + ScreenTools.defaultFontPixelHeight * 0.5\n        radius: ScreenTools.defaultFontPixelWidth * 0.5; color: Qt.rgba(0,0,0,0.70)\n        QGCLabel { id: cameraLabel; anchors.centerIn: parent; color: "white"; font.bold: true; text: qsTr("CAM %1").arg(QGroundControl.videoManager.secondaryHikvisionCamera) }\n    }\n    Rectangle {\n        anchors.right: parent.right; anchors.top: parent.top; anchors.margins: ScreenTools.defaultFontPixelHeight * 0.35\n        width: streamLabel.implicitWidth + ScreenTools.defaultFontPixelWidth * 2; height: streamLabel.implicitHeight + ScreenTools.defaultFontPixelHeight * 0.5\n        radius: ScreenTools.defaultFontPixelWidth * 0.5; color: Qt.rgba(0,0,0,0.70)\n        QGCLabel { id: streamLabel; anchors.centerIn: parent; color: "white"; font.bold: true; text: QGroundControl.videoManager.hikvisionMainStream ? qsTr("MAIN") : qsTr("SUB") }\n    }\n    MouseArea { anchors.fill: parent; cursorShape: Qt.PointingHandCursor; onClicked: QGroundControl.videoManager.swapHikvisionCameras() }\n}\n''')

p='src/FlyView/CMakeLists.txt'; s=read(p)
s=rep(s,'        GuidedValueSlider.qml\n        MultiRotorChecklist.qml\n','        GuidedValueSlider.qml\n        HikvisionSecondVideo.qml\n        MultiRotorChecklist.qml\n','register second video qml'); write(p,s)

# Preserve previous RTSP stability patch
p='src/VideoManager/VideoReceiver/GStreamer/GstSourceFactory.cc'; s=read(p)
if 'configureRtpDepayLossRecovery' not in s:
    s=rep(s,'void configureAutopluggedParser([[maybe_unused]] GstBin* bin, [[maybe_unused]] GstBin* subBin, GstElement* element,\n                                [[maybe_unused]] gpointer data)\n{\n    configureH26xParser(element);\n}\n','''void configureRtpDepayLossRecovery(GstElement* element)\n{\n    GstElementFactory* factory = gst_element_get_factory(element);\n    if (!factory) return;\n    const char* factoryName = gst_plugin_feature_get_name(GST_PLUGIN_FEATURE(factory));\n    const bool h264 = g_strcmp0(factoryName, "rtph264depay") == 0;\n    const bool h265 = g_strcmp0(factoryName, "rtph265depay") == 0;\n    if (!h264 && !h265) return;\n    GObjectClass* c = G_OBJECT_GET_CLASS(element);\n    if (g_object_class_find_property(c, "wait-for-keyframe")) g_object_set(element, "wait-for-keyframe", TRUE, nullptr);\n    if (g_object_class_find_property(c, "request-keyframe")) g_object_set(element, "request-keyframe", TRUE, nullptr);\n}\n\nvoid configureAutopluggedParser([[maybe_unused]] GstBin* bin, [[maybe_unused]] GstBin* subBin, GstElement* element,\n                                [[maybe_unused]] gpointer data)\n{\n    configureH26xParser(element);\n    configureRtpDepayLossRecovery(element);\n}\n''','keyframe recovery')
if 'kRtspMinLatencyMs' not in s:
    s=rep(s,'    // protocols mask enables TCP-interleaved fallback when UDP is blocked; without it\n    // firewalled networks hang until tcp-timeout instead of negotiating TCP.\n    constexpr GstRTSPLowerTrans kRtspProtocols =\n        static_cast<GstRTSPLowerTrans>(GST_RTSP_LOWER_TRANS_UDP | GST_RTSP_LOWER_TRANS_TCP);\n\n    // rtspsrc always owns an internal jitterbuffer, so None maps to zero playout latency and no retransmission.\n    const guint rtspLatencyMs = (config.jitterBuffer == JitterBuffer::None) ? 0u : latencyMs;\n    const gboolean doRetransmission =\n        ((config.jitterBuffer != JitterBuffer::None) && config.doRetransmission) ? TRUE : FALSE;\n    const gboolean dropOnLatency = (config.jitterBuffer == JitterBuffer::Buffered) ? FALSE : TRUE;\n','''    constexpr GstRTSPLowerTrans kRtspProtocols = static_cast<GstRTSPLowerTrans>(GST_RTSP_LOWER_TRANS_TCP);\n    constexpr guint kRtspMinLatencyMs = 120u;\n    constexpr guint kRtspMaxLatencyMs = 250u;\n    guint rtspLatencyMs = latencyMs;\n    if (rtspLatencyMs < kRtspMinLatencyMs) rtspLatencyMs = kRtspMinLatencyMs;\n    else if (rtspLatencyMs > kRtspMaxLatencyMs) rtspLatencyMs = kRtspMaxLatencyMs;\n    const gboolean doRetransmission = FALSE;\n    const gboolean dropOnLatency = TRUE;\n''','tcp bounded latency')
write(p,s)
print('Dual Hikvision patch applied successfully')
